services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=fady
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=honodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hono-network
    ports:
      - "5432:5432"

networks:
  hono-network:
    driver: bridge

volumes:
  postgres-data:
